const actions = {
  GET_LIST_PRODUCT: "GET_LIST_PRODUCT",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GET_COMMENT_FOR_PRODUCT: "GET_COMMENT_FOR_PRODUCT",
  GET_LIST_CUSTOMER: "GET_LIST_CUSTOMER",
  GET_CUSTOMER_BY_ID: "GET_CUSTOMER_BY_ID",
  ADD_COMMENT: "ADD_COMMENT",
  RESET_COMMENT_LIST: "RESET_COMMENT_LIST",
  PRE_FETCH: "PRE_FETCH",
  POST_FETCH: "POST_FETCH,"
};

export { actions };