const actions = {
  GET_LIST_PRODUCT: "GET_LIST_PRODUCT",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GET_COMMENT_FOR_PRODUCT: "GET_COMMENT_FOR_PRODUCT",
  GET_LIST_CUSTOMER: "GET_LIST_CUSTOMER",
};

export { actions };