const actions = {
  GET_LIST_PRODUCT: "GET_LIST_PRODUCT",
  GET_LIST_SEARCH_PRODUCT: "GET_LIST_SEARCH_PRODUCT",
  UPDATE_ACTIVE_PAGE: "UPDATE_ACTIVE_PAGE",
  GET_LIST_SALES_PRODUCT: "GET_LIST_SALES_PRODUCT",
};

export { actions };