const actions = {
    USER_LOGIN_SUBMITTING: "USER_LOGIN_SUBMITTING",
    LOGIN_UPDATE: "LOGIN_UPDATE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_VALIDATION: "LOGIN_VALIDATION",
    RESET_STATE: "RESET_STATE",
  };
  
  export { actions };