const actions = {
    USER_LOGIN_SUBMITTING: "USER_LOGIN_SUBMITTING",
    USER_LOGIN_UPDATE: "USER_LOGIN_UPDATE",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    USER_LOGIN_VALIDATION: "USER_LOGIN_VALIDATION",
    RESET_STATE: "RESET_STATE",
  };
  
  export { actions };