// LOGIN

export const LOGIN_START = "LOGIN_START";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";

export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const SESSION_UPDATE = "SESSION_UPDATE";
export const SESSION_DELETE = "SESSION_DELETE";

// USER

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_COMPLETE = "USER_LOGIN_COMPLETE";

export const USER_UPDATE_EMAIL = "USER_UPDATE_EMAIL";
export const USER_UPDATE_PASSWORD = "USER_UPDATE_PASSWORD";

export const USER_SESSION_UPDATE = "USER_SESSION_UPDATE";
export const USER_SESSION_DELETE = "USER_SESSION_DELETE";